{
 "title": "MC Monitor",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_healthy{server_host=\"hotspot\"}",
     "legendFormat": "hotspot"
    },
    {
     "expr": "minecraft_status_healthy{server_host=\"openj9\"}",
     "legendFormat": "openj9"
    }
   ]
  },
  {
   "title": "CPU Usage in Seconds",
   "type": "timeseries",
   "description": "OpenJ9 vs Hotspot JVM Performance",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"openj9-server\"}[$__interval])",
     "legendFormat": "openj9"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"hotspot-server\"}[$__interval])",
     "legendFormat": "hotspot"
    }
   ]
  },
  {
   "title": "Minecraft Server Container Memory Usage",
   "type": "timeseries",
   "description": "OpenJ9 vs Hotspot JVM Performance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"openj9-server\"}",
     "legendFormat": "openj9"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"hotspot-server\"}",
     "legendFormat": "hotspot"
    }
   ]
  },
  {
   "title": "Minecraft Server Response Time",
   "type": "timeseries",
   "description": "OpenJ9 vs Hotspot JVM Performance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds{server_host=\"openj9\"}",
     "legendFormat": "openj9"
    },
    {
     "expr": "minecraft_status_response_time_seconds{server_host=\"hotspot\"}",
     "legendFormat": "hotspot"
    }
   ]
  }
 ]
}